package StepDefinitions;

import Configuration.Config;
import UtilityClasses.Hooks;
import WebPages.MainPage;
import WebPages.RoLoginPage;
import WebPages.RoRezultatePage;
import WebPages.SalvatAnunturiPage;
import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.testng.Assert;

import java.util.Properties;
import java.util.Random;


public class LoggedInActions {
    WebDriver driver;
    Random random;
    MainPage mainPage;
    RoLoginPage loginPage;
    RoRezultatePage roRezultatePage;
    SalvatAnunturiPage salvatAnunturiPage;
    Properties properties;
    Config props = new Config(properties);
    int maxHearts;

    public LoggedInActions() {
        driver = Hooks.getDriver();
        random = new Random();
        mainPage = new MainPage(driver);
        loginPage = new RoLoginPage(driver);
        roRezultatePage = new RoRezultatePage(driver);
        salvatAnunturiPage = new SalvatAnunturiPage(driver);
    }


    //<Background>
    @Given("the user is logged in")
    public void the_user_is_logged_in() throws InterruptedException {
        mainPage.pressContulMeu();
        loginPage.enterEmail(props.getProperty("username"));
        loginPage.enterPassword(props.getProperty("password"));
        loginPage.pressAutentificareButton();
        Assert.assertEquals(driver.getTitle(), "Intră în cont");
        Thread.sleep(1000);
    }
    //</Background>

    @When("the user clicks on User Menu button")
    public void the_user_clicks_on_User_Menu_button() {
        mainPage.pressUserMenu();
    }
    @And("the user clicks on Logout button")
    public void the_user_clicks_on_Logout_button() throws InterruptedException {
        mainPage.pressLogout();
        Thread.sleep(3000);
    }
    @Then("the user should be logged out")
    public void the_user_should_be_logged_out() {
        Assert.assertTrue(driver.findElement(By.cssSelector(".edaxo2a3 > a:nth-child(1) > span:nth-child(2)")).isDisplayed());
    }
    @And("the user should be redirected to the homepage")
    public void the_user_should_be_redirected_to_the_homepage() {
        Assert.assertEquals(driver.getTitle(), "Storia.ro - anunțuri imobiliare pentru apartamente, case, terenuri");
    }

    @When("the user clicks on multiple Heart buttons")
    public void the_user_clicks_on_multiple_heart_buttons() throws InterruptedException {
        maxHearts = random.nextInt(4) + 1;
        for(int i = 0; i < maxHearts; i++){
            roRezultatePage.pressHeartAt(i);
        }
        Thread.sleep(1000);
    }
    @Then("the selected Heart buttons are filled")
    public void the_selected_heart_buttons_are_filled() throws InterruptedException {
        int c = 0;
        for(int i = 0; i < maxHearts; i++){
            if(roRezultatePage.getHeartStateAt(i))
                c++;
        }
        Assert.assertEquals(c,maxHearts);
        Thread.sleep(5000);
    }
    @Then("the Favourites button counter contains the number of selected items")
    public void the_favourites_button_counter_contains_the_number_of_selected_items() {
        System.out.println("Read attribute of pseudo-element to be implemented");
        //Assert.assertEquals(maxHearts,mainPage.getFavouritesCounterValue());
        /*Pseudo-elements are generated by CSS and are used to add styling or content before or after an element's actual content.
        They are not represented as separate elements in the DOM,
        so you cannot interact with them as you would with regular DOM elements.
         */

    }
    @When("the user clicks on the Favourites dropdown")
    public void the_user_clicks_on_the_favourites_dropdown() {
        mainPage.pressFavourites();
    }
    @When("the Anunturi counter contains the number of selected items")
    public void the_anunturi_counter_contains_the_number_of_selected_items() {
        Assert.assertEquals(mainPage.getAnunturiCounter(),maxHearts);
    }
    @When("the user clicks on the Anunturi button")
    public void the_user_clicks_on_the_anunturi_button() throws InterruptedException {
        mainPage.pressAnunturi();
        Thread.sleep(2000);
    }
    @Then("the Saved page appears")
    public void the_saved_page_appears() {
        System.out.println("step");
    }
    @Then("the Anunturi tab counter contains the number of selected items")
    public void the_anunturi_tab_counter_contains_the_number_of_selected_items() {
        System.out.println("step");
    }
    @When("the user clicks all the Heart buttons")
    public void the_user_clicks_all_the_heart_buttons() throws InterruptedException {
        for(int i = 0; i < maxHearts; i++){
            salvatAnunturiPage.pressHeartAt(0);
            Thread.sleep(1000);
        }

    }

    @Then("the Anunturi tab counter contains zero items")
    public void the_anunturi_tab_counter_contains_zero_items() {
        System.out.println("step");
    }


}
